# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs: 
      environment:
        description: 'Pronnel Ticket ID'     
        required: true
      branch:
        description: 'CM Pronnel Ticket ID'     
        required: true

env:
  BUCKET_ID: "652680819255dd0031fbc00b"
  PRONNEL_AUTH: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoibE5BNk9DTE9BcklsTllCWU01Sj1QLktxTmxDR0F1Qy1FbE5NTE1MZE1lQnZOYUhtSHpEVkJJTDlPOEpoSGpDME9ZR3NJNElYTS5LLktKR25DPEZVRylFU0J6RF5FMk96TyhQbkM6RkRGOERbSytLWUdXRytLckMyT3tQWk1OQV5KZUhASlFHUkdHRmtDKkV7UEVMN0RLRzdPY0hFTGVCRUY9UGpDL0ZWQmVIa04wRG9Idk5NQTxLPUciLCJ1c2VyX2lkIjoiNjM4NDY4YzIzYTdlNmEwMDJkYWE4NWQ5Iiwib3JnX2lkIjoiNjM3YmM1MzIzYmE4MDExY2E0NWM2NmY5IiwiaWF0IjoxNjk3MDIxODMxfQ.a_zLS19PWgT9TAzeTX_qhoFMExPka-_5szKNSsikVsU
# A workflow run is made up of one or more jobs that can run sequentially or in parallel


jobs:
  trigger_pronnel_api:
    runs-on: ubuntu-latest
    steps:
    - name: Send HTTP POST request to Pronnel API
      id: request
      run: |
        response=$(curl -s --location --request POST 'https://api.pronnel.com/board/item/query' \
          --header "Authorization: $PRONNEL_AUTH" \
          --header 'Content-Type: application/json' \
          --data-raw '{"seq_id": [1], "board_id": ["65267fc87b5586003148afcd"]}')
        echo "$response"
        itemResponse=`echo $(jq -r '.itemResponse' <<< "$response")`
        echo "This is item Response Item Response $itemResponse"
        bucket_id=`echo $(jq -r '.[].bucket_id' <<< "$itemResponse")`
        echo "This is item Response Bucket ID $bucket_id"
        echo "bucket_id=$bucket_id" >> $GITHUB_ENV

    - name: Check Global Variable
      run: |
        echo "This is item Response Bucket ID $bucket_id"
        echo "This is BUCKET ID $BUCKET_ID"

    - name: Check Condition
      if: ${{env.BUCKET_ID}} != "$bucket_id"
      run: |
        exit 1
 
    
        

    
  
  
